### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by macyhongg** [macyhongg/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an HTML skeleton
- [x] Add a top-down image of a car within a `div` element
- [x] Ensure that the car will resize as the screen resizes
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
