### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by macyhongg** [macyhongg/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ] Create a main.js file
- [ ] Listen for `keydown` events on the document
- [ ] Rotate the image when the user presses an arrow key
- [ ]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
