### ISSUE TITLE
User can start their car #3

### ISSUE THREAD

**Issue by macyhongg** [macyhongg/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] Add a location to data model to hold the car's `x` and `y` coordinates on the page
- [ ] Use absolute positioning for image
- [ ] When space key is pressed, move the car every 16 milliseconds
- [ ] When the car moves off the page, have it reset to its original position
