### ISSUE TITLE
User can stop their car #4

### ISSUE THREAD

**Issue by macyhongg** [macyhongg/driving-game#7]
## 💰 Motivation
If the user cannot stop their car, it goes off the page.

## 📐 Plan
Stop the car if the user presses space again.

## ✅ Task List
- [ ]  When space key is pressed again, stop the car
- [ ]  If user does not stop the car, it goes off the page
- [ ]  Test all functionality again in a private browsing session.
- [ ]  Fix all errors.
